# Generated by Django 4.0.1 on 2022-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_address_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
