# Generated by Django 4.0.1 on 2022-01-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='Active',
        ),
    ]
